name: "java-app-ci/cd"
on:
 push:
   branches:
      - main
 pull_request:
   branches:
      -main

jobs:
 build-test-deploye:
  runs-on: ubuntu-latest
  steps:
   - name: checkout the code
     uses: actions/checkout@v4

   - name: Install jdk
     uses: actions/setup-java@v4

   - name: install and build maven
     run: mvn clean install

   - name: Run test  
     run: mvn test

   - name: Run package application
     run: mvn package

   - name: Log in to docker-hub
     uses: docker/login-action@v3
     with: 
      username: ${{secrets.DOCKER_USERNAME}}
      password: ${{secrets.DOCKER_PASSWORD}}

   - name: Push Docker Image to Docker Hub   
     uses: docker/build-push-action@v5
     with:
        context: .
        push: true
        tags: baishla123/java-springboot-web-application:latest
